### ISSUE TITLE
Unable to reduce the lat/long range

### ISSUE THREAD

**Issue by heliosCanlilar** [abhinavyesss/graphcast-predict#2]
The scripts work great when using the default values you put in for lat and long range, however when I reduce the ranges to say:
lat_range = range(-180, -175, 1) 
lon_range = range(0, 6, 1) 

I get the following error:

`Traceback (most recent call last):
  File "/Users/edenwaller/Documents/GitHub/helios-data-science/experiments/eden/weather/graph_cast_forecasting/prediction.py", line 336, in <module>
    values = {value:makeXarray(values[value]) for value in values}
  File "/Users/edenwaller/Documents/GitHub/helios-data-science/experiments/eden/weather/graph_cast_forecasting/prediction.py", line 336, in <dictcomp>
    values = {value:makeXarray(values[value]) for value in values}
  File "/Users/edenwaller/Documents/GitHub/helios-data-science/experiments/eden/weather/graph_cast_forecasting/prediction.py", line 293, in makeXarray
    data = modifyCoordinates(data)
  File "/Users/edenwaller/Documents/GitHub/helios-data-science/experiments/eden/weather/graph_cast_forecasting/prediction.py", line 284, in modifyCoordinates
    data[var] = varArray.isel(**{coord: 0 for coord in nonIndices})
  File "/Users/edenwaller/anaconda3/envs/graph-cast10-env/lib/python3.10/site-packages/xarray/core/dataarray.py", line 1480, in isel
    variable = self._variable.isel(indexers, missing_dims=missing_dims)
  File "/Users/edenwaller/anaconda3/envs/graph-cast10-env/lib/python3.10/site-packages/xarray/core/variable.py", line 1130, in isel
    return self[key]
  File "/Users/edenwaller/anaconda3/envs/graph-cast10-env/lib/python3.10/site-packages/xarray/core/variable.py", line 812, in __getitem__
    data = as_indexable(self._data)[indexer]
  File "/Users/edenwaller/anaconda3/envs/graph-cast10-env/lib/python3.10/site-packages/xarray/core/indexing.py", line 1336, in __getitem__
    return array[key]
IndexError: index 0 is out of bounds for axis 0 with size 0`

I'm using Python 10 though which was not what your yaml suggested. Not sure if that's part of the problem.

**Comment by abhinavyesss** [comment]
Graphcast will not work on a subset of coordinates. It needs data from all 360 longitudes and 181 latitudes.

**Comment by heliosCanlilar** [comment]
Gottcha okay. Then in that case should the latitudes be -90 to 90? Instead
of -180 to 180

**Comment by abhinavyesss** [comment]
Yes it should be, looks like I have made an error in initializing that range values. However, since we take an inner merge the result will be the same, it will make some unneeded calculations though.

The correction has been made.
